// <auto-generated />
using System;
using LikeButtonProject.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LikeButtonProject.Migrations
{
    [DbContext(typeof(LikeButtonContext))]
    [Migration("20201204180038_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LikeButtonProject.Entities.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_article");

                    b.Property<string>("Content")
                        .HasColumnType("varhcar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("tb_articles");
                });

            modelBuilder.Entity("LikeButtonProject.Entities.Like", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_like");

                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("LikeInstant")
                        .HasColumnType("datetime2")
                        .HasColumnName("liked_instant");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("tb_likes");
                });

            modelBuilder.Entity("LikeButtonProject.Entities.Like", b =>
                {
                    b.HasOne("LikeButtonProject.Entities.Article", "Article")
                        .WithMany("Likes")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LikeButtonProject.Entities.Article", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
